spring:
  application:
    name: appcatalyst
    description: this is application

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:postgresql://localhost:9010/appcatalyst
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      timeout: 10m
      chat:
        model: minimax/minimax-m3:free
        temperature: 0.0
        max-tokens: 262144

jwt:
  secret-key: TG7rAfx79XsVtPWBx-6c6D4uImcPPVvPDGhRfUHiVFheUjR7Bz7Zqk6h9DrmN5jprB5kmHBPvbycqooVL83ljw

stripe:
  api:
    secret: ${STRIPE_API_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects