spring:
  application:
    name: appcatalyst
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:5432/appcatalyst
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

jwt:
  secret-key: TG7rAfx79XsVtPWBx-6c6D4uImcPPVvPDGhRfUHiVFheUjR7Bz7Zqk6h9DrmN5jprB5kmHBPvbycqooVL83ljw
